/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSocialRouteImport } from './routes/_authenticated/social'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedLocalRouteImport } from './routes/_authenticated/local'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedPetNovoRouteImport } from './routes/_authenticated/pet.novo'
import { Route as AuthenticatedPetPetIdRouteImport } from './routes/_authenticated/pet.$petId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSocialRoute = AuthenticatedSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLocalRoute = AuthenticatedLocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPetNovoRoute = AuthenticatedPetNovoRouteImport.update({
  id: '/pet/novo',
  path: '/pet/novo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPetPetIdRoute = AuthenticatedPetPetIdRouteImport.update({
  id: '/pet/$petId',
  path: '/pet/$petId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/local': typeof AuthenticatedLocalRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/social': typeof AuthenticatedSocialRoute
  '/pet/$petId': typeof AuthenticatedPetPetIdRoute
  '/pet/novo': typeof AuthenticatedPetNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/local': typeof AuthenticatedLocalRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/social': typeof AuthenticatedSocialRoute
  '/pet/$petId': typeof AuthenticatedPetPetIdRoute
  '/pet/novo': typeof AuthenticatedPetNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/local': typeof AuthenticatedLocalRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/social': typeof AuthenticatedSocialRoute
  '/_authenticated/pet/$petId': typeof AuthenticatedPetPetIdRoute
  '/_authenticated/pet/novo': typeof AuthenticatedPetNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/local'
    | '/perfil'
    | '/social'
    | '/pet/$petId'
    | '/pet/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/local'
    | '/perfil'
    | '/social'
    | '/pet/$petId'
    | '/pet/novo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/home'
    | '/_authenticated/local'
    | '/_authenticated/perfil'
    | '/_authenticated/social'
    | '/_authenticated/pet/$petId'
    | '/_authenticated/pet/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/social': {
      id: '/_authenticated/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AuthenticatedSocialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/local': {
      id: '/_authenticated/local'
      path: '/local'
      fullPath: '/local'
      preLoaderRoute: typeof AuthenticatedLocalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pet/novo': {
      id: '/_authenticated/pet/novo'
      path: '/pet/novo'
      fullPath: '/pet/novo'
      preLoaderRoute: typeof AuthenticatedPetNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pet/$petId': {
      id: '/_authenticated/pet/$petId'
      path: '/pet/$petId'
      fullPath: '/pet/$petId'
      preLoaderRoute: typeof AuthenticatedPetPetIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLocalRoute: typeof AuthenticatedLocalRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedSocialRoute: typeof AuthenticatedSocialRoute
  AuthenticatedPetPetIdRoute: typeof AuthenticatedPetPetIdRoute
  AuthenticatedPetNovoRoute: typeof AuthenticatedPetNovoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLocalRoute: AuthenticatedLocalRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedSocialRoute: AuthenticatedSocialRoute,
  AuthenticatedPetPetIdRoute: AuthenticatedPetPetIdRoute,
  AuthenticatedPetNovoRoute: AuthenticatedPetNovoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
